# Getting Started

Content: 

- basic mathematics operations, 
- broadcasting, 
- indexing, 
- slicing, 
- memory saving, 
- conversion to other Python objects.

In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape


torch.Size([12])

In [4]:
x.numel()

12

In [5]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
# randomly sample the values for each element in a tensor from some probability distribution
torch.randn(3, 4)

tensor([[-0.0788,  1.0642, -0.9423,  1.4727],
        [-0.9608,  1.6972,  0.5499, -0.0694],
        [-0.6865,  0.6748,  0.9123, -0.7705]])

In [9]:
# specify the exact values for each element
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

# Operations

## *elementwise* operations.

In [12]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # The ** operator is exponentiation

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [13]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

## Concate

In [14]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

## construct a binary tensor via logical statements

In [15]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

## Summing

In [16]:
x.sum()

tensor(66.)

# Broadcasting Mechanism

- First, expand one or both arrays by copying elements appropriately so that after this transformation, the two tensors have the same shape. 
- Second, carry out the elementwise operations on the resulting arrays.

In [17]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

In [18]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# Indexing and Slicing

In [19]:
x[-1], x[1:3]

(tensor([ 8.,  9., 10., 11.]), tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [20]:
x[1, 2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [21]:
x[0:2, :] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

# Saving Memory

**Running operations can cause new memory to be allocated to host results. For example, if we write y = x + y, we will dereference the tensor that y used to point to and instead point y at the newly allocated memory.**

In [22]:
before = id(y)
y = y + x
id(y) == before

False

**Drawbacks:**

- First, we do not want to run around allocating memory unnecessarily all the time. Typically, we will want to perform these updates **in place**. 
- Second, **we might point at the same parameters from multiple variables**. If we do not update in place, other references will still point to the old memory location, making it possible for parts of our code to inadvertently reference stale parameters.

In [23]:
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

('id(z):', 4903255968)
('id(z):', 4903255968)


If the value of x is not reused in subsequent computations, we can also use x[:] = x + y or x += y to reduce the memory overhead of the operation.

In [26]:
before = id(x)
x += y
id(x) == before

True

# Conversion to Other Python Objects

In [27]:
a = x.numpy()
b = torch.tensor(a)
type(a), type(b)

(numpy.ndarray, torch.Tensor)

In [28]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# The d2l Package

In [29]:
#@save
numpy = lambda a: a.detach().numpy()
size = lambda a: a.numel()
reshape = lambda a, *args: a.reshape(*args)
ones = torch.ones
zeros = torch.zeros

# Exercises

1. Run the code in this section. Change the conditional statement x == y in this section to x < y or x > y, and then see what kind of tensor you can get.

In [30]:
x < y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [31]:
x > y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

2. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?

In [33]:
a = torch.arange(3).reshape((3, 1, 1))
b = torch.arange(2).reshape((1, 2, 1))
a, b

(tensor([[[0]],
 
         [[1]],
 
         [[2]]]), tensor([[[0],
          [1]]]))

In [34]:
a + b

tensor([[[0],
         [1]],

        [[1],
         [2]],

        [[2],
         [3]]])

In [35]:
(a + b).shape

torch.Size([3, 2, 1])